### ISSUE TITLE
onTouchTap Error

### ISSUE THREAD

**Issue by whnunlife** [franciskim722/materialui-pagination#1]
Getting the following error:

```
warning.js:36 Warning: Unknown prop `onTouchTap` on <span> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in span (created by EnhancedButton)
    in EnhancedButton (created by ListItem)
    in div (created by ListItem)
    in ListItem (created by MenuItem)
    in MenuItem (created by Menu)
    in div (created by List)
    in List (created by Menu)
    in div (created by Menu)
    in ClickAwayListener (created by Menu)
    in Menu (created by DropDownMenu)
    in div (created by Paper)
    in Paper (created by PopoverAnim
```
Not sure if this error is also causing the following issue. But when I select the drop down, to change say the number of pages displayed, from "100" to "200", I'm not getting the updateRows function to be called.

**Comment by franciskim722** [comment]
Could you provide a snippet of how you are using the component?

**Comment by whnunlife** [comment]
@franciskim722 Sorry, been busy.

Here is a Gist of my main app.js, which I'm using "react-boilerplate".

https://gist.github.com/whnunlife/5bb93bf045fd29aedfb03d19feb27f8d

Outside of that, in my container / component, i'm importing:

```import Pagination from 'materialui-pagination';```

then returning the pagination component:

```
<div className="table-pagination flex justify-end items-center">
  <Pagination
     total={people.pagination.total}
     rowsPerPage={rowsPerPage}
     page={people.pagination.page}
     numberOfRows={100}
     updateRows={this.updateRows}
  />
</div>
```

**Comment by franciskim722** [comment]
Which version of material-ui are you using? 

Can you show the dependencies object in your package.json?

**Comment by whnunlife** [comment]
@franciskim722 Here u go: https://gist.github.com/whnunlife/c56ef88d31a39195ed158e29ceefc337

**Comment by franciskim722** [comment]
@whnunlife In your App component did you import and use MuiThemeProvider?

**Comment by whnunlife** [comment]
@franciskim722 Yes sir...
