### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by marcjps** [franciskim722/materialui-pagination#3]
I think selecting items in the dropdown lists doesn't work in Firefox.  

In the console it logs "ReferenceError: event is not defined".

The problem can be replicated on the demo/index.html.  I am currently using Firefox 52.4.0.

Could you help?

**Comment by bacancykrina** [comment]
I have same issue and I'm using Firefox 54.0 . 

Any solution ?

**Comment by marcjps** [comment]
I think it is because "event" is not specified as a parameter for the functions selectRowsPerPage and selectPageNumber.   The open pull requests contains the same changes.  I took the source from src/index.js and applied the changes on my copy and it works in Firefox for me now.

**Comment by VILATTI** [comment]
Same issue with version 57.0.
Guys, please merge pull request to fix this issue.

**Comment by bacancykrina** [comment]
@marcjps How did you take code? 
I want to make it like when next time i do npm install, it should not generate same error.

**Comment by marcjps** [comment]
@bacancykrina I downloaded the master zip file.  For the time being I made a new component in my project, put the code there and fixed it, so now I'm not using it from npm.  If the owner fixes it I could go back.

**Comment by bacancykrina** [comment]
Thanks @marcjps 
I have asked owner for that. till i'll do the same.

**Comment by rearmitage** [comment]
#2 Just linking to my pull request that would fix this. I submitted it a while ago and he hasn't pulled it in so I just ended up copying it into a component in the project I was working in.

**Comment by franciskim722** [comment]
Thanks @rearmitage for the help. I've been caught up with some personal things, but thank you!
